services:
  db:
    image: postgres:14.12-bullseye
    ports:
      # [Expose](https://docs.docker.com/compose/compose-file/05-services/#expose)
      - "5050:5432"
    environment:
      # [Environment Variables for Postgres Img](https://hub.docker.com/_/postgres)
      - POSTGRES_PASSWORD=admin
    volumes:
      # This is where the DDL would go, for now it just is a placeholder.
      - "./core/src/main/sql/:/docker-entrypoint-initdb.d/"
  api:
    build:
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    environment:
      # Default User & Password already specified in .properties
      # [How we resolve hostname 'db'](https://docs.docker.com/compose/networking/)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gm_song_storage
      # We are not mounting volumes to persist the data, we will be recreating each time anyway.
      - SPRING.JPA.GENERATE-DDL=true
    depends_on:
      - db
