name: gm-song-storage-dev
services:
  db:
    image: postgres:latest
    container_name: gm-song-storage-dev-db
    ports:
      # [Expose](https://docs.docker.com/compose/compose-file/05-services/#expose)
      - "5151:5432"
    environment:
      # [Environment Variables for Postgres Img](https://hub.docker.com/_/postgres)
      - POSTGRES_DB=gm_song_storage
      - POSTGRES_PASSWORD=admin
    volumes:
      # This is where the DDL would go, for now it just is a placeholder.
      - "./core/src/main/sql/:/docker-entrypoint-initdb.d/"
  api:
    image: gm-song-storage-api:dev
    build:
      dockerfile: "Dockerfile"
    container_name: gm-song-storage-dev-api
    ports:
      - "8080:8080"
    environment:
      # Default User & Password already specified in .properties
      # [How we resolve hostname 'db'](https://docs.docker.com/compose/networking/)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gm_song_storage
      - SPRING.JPA.OPEN-IN-VIEW=false
    depends_on:
      - db
